name: CI

permissions: {}

on:
  pull_request:
  push:
    branches:
      - alpha
      - beta
      - main
      - renovate/**

jobs:
  ci-optimization:
    name: CI optimization
    uses: dargmuesli/github-actions/.github/workflows/ci-optimization.yml@0ee6252ffb1543f94dbf5acd108d1affd8b787d0 # 5.2.4
    permissions:
      pull-requests: read
  release_semantic_dry:
    needs: ci-optimization
    if: needs.ci-optimization.outputs.continue == 'true'
    name: Release (semantic, dry)
    uses: dargmuesli/github-actions/.github/workflows/release-semantic.yml@0ee6252ffb1543f94dbf5acd108d1affd8b787d0 # 5.2.4
    permissions:
      contents: write
      id-token: write
    secrets:
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
    with:
      DRY_RUN: true
      EXTRA_PLUGINS: |
        semantic-release-replace-plugin
      GH_APP_ID: ${{ vars.GH_APP_ID }}
  build:
    name: Build
    uses: dargmuesli/github-actions/.github/workflows/docker.yml@0ee6252ffb1543f94dbf5acd108d1affd8b787d0 # 5.2.4
    needs: release_semantic_dry
    permissions:
      packages: write
    with:
      ARTIFACT_PATH: .
      BUILD_TARGET_RELEASE: test
      TAG: ${{ needs.release_semantic_dry.outputs.new_release_version }}
  coverage:
    name: Upload Coverage
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: build-artifact
      - name: Extract coverage artifact
        run: |
          tar -xzf build-artifact.tar
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  release_semantic:
    needs: build
    name: Release (semantic)
    uses: dargmuesli/github-actions/.github/workflows/release-semantic.yml@0ee6252ffb1543f94dbf5acd108d1affd8b787d0 # 5.2.4
    permissions:
      contents: write
      id-token: write
    secrets:
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
    with:
      EXTRA_PLUGINS: |
        semantic-release-replace-plugin
      GH_APP_ID: ${{ vars.GH_APP_ID }}
