name: CI

permissions: {}

on:
  pull_request:
  push:
    branches:
      - alpha
      - beta
      - main
      - renovate/**

jobs:
  ci-optimization:
    name: CI optimization
    uses: dargmuesli/github-actions/.github/workflows/ci-optimization.yml@294d370b270732cd3653e2961037405666ade3b8 # 5.9.9
    permissions:
      pull-requests: read
  release_semantic_dry:
    needs: ci-optimization
    if: needs.ci-optimization.outputs.continue == 'true'
    name: Release (semantic, dry)
    uses: dargmuesli/github-actions/.github/workflows/release-semantic.yml@294d370b270732cd3653e2961037405666ade3b8 # 5.9.9
    permissions:
      contents: write
      id-token: write
    secrets:
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
    with:
      DRY_RUN: true
      EXTRA_PLUGINS: |
        semantic-release-replace-plugin
      GH_APP_ID: ${{ vars.GH_APP_ID }}
  build:
    name: Build
    uses: dargmuesli/github-actions/.github/workflows/docker.yml@294d370b270732cd3653e2961037405666ade3b8 # 5.9.9
    needs: release_semantic_dry
    permissions:
      packages: write
    with:
      ARTIFACT_PATH: .
      BUILD_TARGET_RELEASE: test
      PLATFORMS: linux/amd64,linux/arm64
      TAG: ${{ needs.release_semantic_dry.outputs.new_release_version }}
  coverage:
    name: Upload Coverage
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@9000827ccba6bdab643e8b6fd33ac0654aef8333 # v8.0.2
        with:
          name: build-artifact
      - name: Extract coverage artifact
        run: |
          tar -xzf build-artifact.tar
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  release_semantic:
    needs: build
    name: Release (semantic)
    uses: dargmuesli/github-actions/.github/workflows/release-semantic.yml@294d370b270732cd3653e2961037405666ade3b8 # 5.9.9
    permissions:
      contents: write
      id-token: write
    secrets:
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
    with:
      EXTRA_PLUGINS: |
        semantic-release-replace-plugin
      GH_APP_ID: ${{ vars.GH_APP_ID }}
